# Generated by Django 6.0.5 on 2026-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bets", "0002_alter_bet_outcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="payment_validated",
            field=models.BooleanField(default=False),
        ),
    ]
