# Generated by Django 6.0.5 on 2026-05-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bets", "0003_bet_payment_validated"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="away_team",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="match",
            name="home_team",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="match",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
